### ISSUE TITLE
Markbot issues 

### ISSUE THREAD

**Issue by PennyVu** [PennyVu/dinosaur-designs#2]
@KarenMendozaGarza 
Hello, I need help with the markbot
![Screen Shot 2022-03-07 at 11 17 57 AM](https://user-images.githubusercontent.com/97452348/157074294-d1ed8a2a-ee37-464d-aeaa-378bf81d017a.png)

**Comment by KarenMendozaGarza** [comment]
For Dinos R us, its just an issue with the quotes. It wants two right ones. Try pasting this : Dinos ’R’ Us
For line 18, it wants you to specify the font family. Just copy and paste the font family from your html into your h1.

**Comment by KarenMendozaGarza** [comment]
and add a space after the comma between your selectors on line 18

**Comment by KarenMendozaGarza** [comment]
Hi Penny, 
Did you still need help with this issue?
If not, please remember to close your issues they have been resolved:)

**Comment by PennyVu** [comment]
oh Hi, I'm sorry I forgot about it. Thanks for reminding me!
